let nombre = "Carlos";
let edad = 20;
let altura = 1.75;
let casado = false;
document.write("Nombre: ", nombre);
document.write("<br>");
document.write("Edad: ", edad);
document.write("<br>");
document.write("Altura: ", altura);
document.write("<br>");
document.write("Casado: ", casado);
document.write("<br>");
let nombre2;
nombre2 = prompt ("Digite su nombre: ");
document.write(nombre2, "<br>");
let num1 = prompt ("Digite numero 1: ");
let num2 = prompt ("Digite numero 2: ");
let num3 = num1 * num2;
let resultado = parseInt(num1) + parseInt(num2);
document.write(resultado, "-", num3); 
